---
- hosts: all
  become: yes
  become_user: root
  gather_facts: true

  tasks:

    - name: configure timezone
      timezone: 
        name: Europe/Paris

    - name: install ansible
      apt:
        name:  ansible
        state: latest
      when: "'ansible-host' in inventory_hostname"

    - name: create a provisioning user with ssh key on ansible host
      user:
        name: provisioning
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        state: present
      when: "'ansible-host' in inventory_hostname"

    - name: create ansible directory
      file: /home/vagant/ansible
      state: directory

    - name: add ansible.cfg to ansible dir
      copy:
        dest: /home/vagrant/ansible/ansible.cfg
        content: "[defaults] \n inventory = ./hosts"
      when: "'ansible-host' in inventory_hostname"

    - name: create the ansible hosts file
      copy:
        dest: /home/vagrant/ansible/hosts
        content: "client-host"
      when: "'ansible-host' in inventory_hostname"
