# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# Define VMs with static private IP addresses, vcpu, memory and vagrant-box.
  boxes = [
    {
      :name => "vagrant-dl-web-d",
      :box => "gusztavvargadr/windows-server",
      :ram => 2048,
      :vcpu => 2,
      :ip => "10.0.0.2"
    },
  ]

  # Provision each of the VMs.
  boxes.each do |opts|

    config.vm.define opts[:name] do |config|
      # config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
      config.vm.box = opts[:box]
      config.vm.hostname = opts[:name]
      config.vm.provider :virtualbox do |v| 
        v.memory = opts[:ram]
        v.cpus = opts[:vcpu]
      end
      config.vm.network :private_network, ip: opts[:ip]
      
      # Switch protocol to winRM
      config.vm.communicator = "winrm"
      # Admin user name and password
      config.winrm.username = "vagrant"
      config.winrm.password = "vagrant"

      config.vm.provision :ansible do |ansible| 
        ansible.verbose = "v"
        ansible.playbook = "install.yml"
       # workaround for SSL error due to default winrm bind to https (https://github.com/hashicorp/vagrant/issues/10765)
        ansible.raw_arguments = ["-e", "ansible_winrm_scheme=http"]
      end
      
     end
  end
end